# Generated by Django 5.2.16 on 2026-07-19 16:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConnectionStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(choices=[('discord', 'Discord Bot'), ('telegram', 'Telegram Bot')], max_length=20, unique=True)),
                ('is_connected', models.BooleanField(default=False)),
                ('last_checked', models.DateTimeField(blank=True, null=True)),
                ('last_success', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, default='')),
                ('details', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'Connection Status',
                'verbose_name_plural': 'Connection Statuses',
            },
        ),
        migrations.CreateModel(
            name='ForwardRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Short name for this rule (e.g. "ops", "CTA")', max_length=100)),
                ('discord_channel_id', models.CharField(help_text='Discord channel ID to listen to', max_length=100)),
                ('discord_channel_name', models.CharField(blank=True, help_text='Human-readable Discord channel name (for display)', max_length=255)),
                ('telegram_target', models.CharField(help_text='Telegram chat ID or @username to forward to', max_length=255)),
                ('telegram_target_type', models.CharField(choices=[('chat_id', 'Chat ID'), ('username', 'Username/@')], default='chat_id', max_length=20)),
                ('keyword_filter', models.CharField(blank=True, default='', help_text='Comma-separated keywords. If set, only messages containing one of these words trigger forwarding. Leave empty for all messages.', max_length=500)),
                ('is_enabled', models.BooleanField(default=True)),
                ('priority', models.IntegerField(default=0, help_text='Higher priority rules are checked first')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Forward Rule',
                'verbose_name_plural': 'Forward Rules',
                'ordering': ['-priority', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TelegramGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('telegram_chat_id', models.CharField(max_length=100, unique=True)),
                ('chat_type', models.CharField(choices=[('supergroup', 'Supergroup'), ('group', 'Group'), ('channel', 'Channel')], default='supergroup', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Telegram Group',
                'verbose_name_plural': 'Telegram Groups',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ForwardHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_channel', models.CharField(max_length=255)),
                ('target_channel', models.CharField(max_length=255)),
                ('message_preview', models.TextField(blank=True, default='', max_length=500)),
                ('discord_message_id', models.CharField(blank=True, default='', max_length=100)),
                ('forwarded_at', models.DateTimeField(auto_now_add=True)),
                ('success', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True, default='')),
                ('rule', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history', to='aa_discord_telegram_bridge.forwardrule')),
            ],
            options={
                'verbose_name': 'Forward History',
                'verbose_name_plural': 'Forward History',
                'ordering': ['-forwarded_at'],
            },
        ),
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_chat_id', models.CharField(blank=True, default='', help_text='Telegram user chat ID (obtained automatically)', max_length=100)),
                ('telegram_user_id', models.BigIntegerField(blank=True, help_text='Telegram numeric user ID', null=True)),
                ('telegram_username', models.CharField(blank=True, default='', max_length=100)),
                ('is_active', models.BooleanField(default=False, help_text='Whether the user has enabled Telegram notifications')),
                ('notifications_enabled', models.BooleanField(default=True, help_text='Master toggle for all notifications')),
                ('linked_at', models.DateTimeField(auto_now_add=True)),
                ('last_validated', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='telegram_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Telegram User',
                'verbose_name_plural': 'Telegram Users',
            },
        ),
    ]
