# Generated by Django 5.2.16 on 2026-07-19 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aa_discord_telegram_bridge', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DTBSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_bot_token', models.CharField(blank=True, default='', help_text='Telegram Bot API token', max_length=255)),
                ('discord_bot_token', models.CharField(blank=True, default='', help_text='Discord Bot token', max_length=255)),
                ('discord_guild_id', models.CharField(blank=True, default='', help_text='Discord Guild (Server) ID', max_length=100)),
                ('alliance_id', models.PositiveIntegerField(blank=True, help_text='EVE Alliance ID to enforce membership. Leave empty to disable.', null=True)),
                ('telegram_webhook_url', models.CharField(blank=True, default='', help_text='Telegram webhook URL for receiving updates (for user linking)', max_length=500)),
                ('github_repo', models.CharField(blank=True, default='', help_text='GitHub repo for updates, e.g. user/repo', max_length=300)),
                ('version', models.CharField(default='0.1.0', max_length=50)),
            ],
            options={
                'verbose_name': 'DTB Settings',
                'verbose_name_plural': 'DTB Settings',
            },
        ),
    ]
