# Generated by Django 5.2.16 on 2026-07-19 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aa_discord_telegram_bridge', '0003_seed_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dtbsettings',
            name='version',
            field=models.CharField(default='1.0.1', max_length=50),
        ),
    ]
