# Generated by Django 5.2.16 on 2026-07-19 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aa_discord_telegram_bridge', '0004_alter_dtbsettings_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='dtbsettings',
            name='autostart_bot',
            field=models.BooleanField(default=False, help_text='Auto-start the Discord forwarder bot inside Alliance Auth (no separate process needed). Requires a restart to take effect.'),
        ),
        migrations.AlterField(
            model_name='dtbsettings',
            name='version',
            field=models.CharField(default='1.0.4', max_length=50),
        ),
    ]
