# Generated by Django 5.2.16 on 2026-07-19 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aa_discord_telegram_bridge', '0005_dtbsettings_autostart_bot_alter_dtbsettings_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dtbsettings',
            name='github_repo',
            field=models.CharField(blank=True, default='radioactive68/AUTH-Discord-Telegram-Bridge', help_text='GitHub repo for updates, e.g. user/repo', max_length=300),
        ),
        migrations.AlterField(
            model_name='dtbsettings',
            name='version',
            field=models.CharField(default='1.0.17', max_length=50),
        ),
    ]
