# Generated by Django 5.2.16 on 2026-07-19 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aa_discord_telegram_bridge', '0006_alter_dtbsettings_github_repo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_heartbeat', models.DateTimeField(blank=True, null=True)),
                ('pid', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Bot Status',
                'verbose_name_plural': 'Bot Status',
            },
        ),
        migrations.AlterModelOptions(
            name='dtbsettings',
            options={'permissions': (('access_dtb', 'Can access Discord-Telegram Bridge'), ('manage_dtb_rules', 'Can manage DTB rules and settings'), ('view_forward_history', 'Can view forward history')), 'verbose_name': 'DTB Settings', 'verbose_name_plural': 'DTB Settings'},
        ),
        migrations.AlterField(
            model_name='dtbsettings',
            name='version',
            field=models.CharField(default='1.0.20', max_length=50),
        ),
    ]
