# Generated by Django 5.2.16 on 2026-07-19 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aa_discord_telegram_bridge', '0007_botstatus_alter_dtbsettings_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dtbsettings',
            name='verification_days',
            field=models.PositiveIntegerField(default=30, help_text='Days before a verified Telegram user must re-verify via /start. Users who do not re-verify in time are kicked from Telegram groups. Set 0 to disable periodic re-verification.'),
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='telegram_verified_at',
            field=models.DateTimeField(blank=True, help_text='When the user last verified via /start (used for periodic re-verification).', null=True),
        ),
        migrations.AlterField(
            model_name='dtbsettings',
            name='version',
            field=models.CharField(default='1.0.22', max_length=50),
        ),
    ]
