# Generated by Django 5.2.16 on 2026-07-19 21:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aa_discord_telegram_bridge', '0008_dtbsettings_verification_days_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramLinkRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.CharField(max_length=64, unique=True)),
                ('telegram_user_id', models.CharField(blank=True, default='', max_length=64)),
                ('username', models.CharField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Telegram Link Request',
                'verbose_name_plural': 'Telegram Link Requests',
            },
        ),
        migrations.AlterField(
            model_name='dtbsettings',
            name='version',
            field=models.CharField(default='1.0.26', max_length=50),
        ),
    ]
