# Generated by Django 5.2.16 on 2026-07-19 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aa_discord_telegram_bridge', '0009_telegramlinkrequest_alter_dtbsettings_version'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dtbsettings',
            name='verification_days',
        ),
        migrations.RemoveField(
            model_name='telegramuser',
            name='telegram_verified_at',
        ),
        migrations.AlterField(
            model_name='dtbsettings',
            name='version',
            field=models.CharField(default='1.0.28', max_length=50),
        ),
    ]
