# Generated by Django 5.2.16 on 2026-07-23 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aa_discord_telegram_bridge', '0011_remove_dtbsettings_github_repo_and_version'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telegramuser',
            name='notifications_enabled',
        ),
    ]
