# Generated by Django 5.2.16 on 2026-07-25 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aa_discord_telegram_bridge', '0013_telegramgroup_auto_invite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dtbsettings',
            name='autostart_bot',
            field=models.BooleanField(default=True, help_text='Auto-start the Discord forwarder bot inside Alliance Auth (no separate process needed). Requires a restart to take effect.'),
        ),
    ]
